name: .NET Core Desktop
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'
  # additional events omitted for brevity
  jobs:
  build:
    runs-on:vvh-self-hosted
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '6.0.x' ]
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
