name: .NET Core Desktop
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'
 
  jobs:
  build:
    runs-on:vvh-self-hosted
   
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
