name: .NET Core Desktop
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'
 
  steps:
  build:
    runs-on:vvh-self-hosted
   


